### ISSUE TITLE
CPU Timing (Too fast?)

### ISSUE THREAD

**Issue by Mouseboy007** [MiSTer-devel/Archie_MiSTer#10]
Several games appear to run very fast relative to a physical machine, or using the same ADF Disk (or HDF Disk) & RiscOS Rom combination (3.10) in Arculator 0.99.

For example, Pacmania and ChaosEngine

Also, as there were several Archimedes models would it be possible to have a CPU speed toggle like the AO486 core?

Thanks!

**Comment by sorgelig** [comment]
CPU and chipset are not cycle accurate. So even setting to some specific clock won't make it work as original HW.

**Comment by Mouseboy007** [comment]
> CPU and chipset are not cycle accurate. So even setting to some specific clock won't make it work as original HW.

Many thanks, hopefully as development progresses for this core cycle accuracy will improve. The community really appreciate the hard work that has gone into this already!

Would it be possible to have a toggle switch anyway just to decrease the speed by say 10%, 20% etc so that if software runs too fast the user can artificially dial it back to something perceptibly more accurate for the game/application being used? 

Again, Thanks!

(P.S. I meant Cannon Fodder, not Chaos Engine - I've not yet tested Chaos Engine!)

**Comment by sorgelig** [comment]
Cannon Fodder was actually the game requiring more CPU speed and became more or less good after last CPU speed increase. So i don't understand what you mean by talking about Cannon Fodder.

**Comment by Mouseboy007** [comment]
> Cannon Fodder was actually the game requiring more CPU speed and became more or less good after last CPU speed increase. So i don't understand what you mean by talking about Cannon Fodder.

Perhaps my perception, I thought it ran a little too fast - however, Pacmania is definitely running much too fast (sorry if I'm wrong on Cannon Fodder).

**Comment by Mouseboy007** [comment]
A little update on the issue - via HDMI, the core seems too fast (with refresh rates of 60hz or variable from the MiSTer core). 
Via a 50hz CRT (via VGA>RGB Scart) the timing seems fine (even on 60hz).

**Comment by sorgelig** [comment]
Timings are independent from video output.

**Comment by Mouseboy007** [comment]
Hi Sorgelig - apologies, after further testing, user-error on my part
