### ISSUE TITLE
1.6MB ADF Floppy Images not supported

### ISSUE THREAD

**Issue by zompiexx** [MiSTer-devel/Archie_MiSTer#15]
First of all, thanks for creating such a great Archie core.

Whilst I can read 800KB Floppy images fine, 1.6MB Floppy Images don't seem to work. Is this something that could be added as it would be useful for copying software, especially single disc games etc. - which even compressed are often too large for an 800KB image.

Best regards,

Andy

**Comment by hubersn** [comment]
RISC OS supports 1.6MB floppy discs/drives only if "PC-style I/O" is detected. The MIST(er) core implements the WD1772 as floppy controller, so only 800KB is available.

Maybe you could try ADFFS as a workaround, mounting the floppy images from inside RISC OS from the HD image. In early MIST(er) core versions, ADFFS didn't work properly however, hanging the machine.

On the topic of copying - use harddisc image files for data transfer with the help of Arculator v2.0, this is a lot less painless than transferring data via floppy images.

**Comment by zompiexx** [comment]
Thanks for the info and the suggestion. For transferring between machines I am already using Arculator v2.0 and HDF images, but the 1.6MB floppy support would have been useful for transferring to/from my hardware A3020 (via the Gotek).
