### ISSUE TITLE
HDF ADFS HDD images not recognized

### ISSUE THREAD

**Issue by PaulSpek** [MiSTer-devel/Archie_MiSTer#8]
Using MiSTer v200821, ARCHIE v200821.

Set IDEFSDiscs to 2 in CMOS. Assigned known working (RPC Emu, Arculator) hdf images to HDD 0 and HDD 1 in the OSD. Reset the core using ALT-ALT-CTRL.

IDE:4 and IDE:5 appear in the icon bar. When trying to access RiscOS responds "Disc not understood - has it been formatted?"

Is there a known working hdf file available?

**Comment by sorgelig** [comment]
I don't know if there are different filesystems for HDD in Archie.
I found several user pre-made disks on MiST (Atari) forum - they work fine. When you setup IDE in config you set filesyetem to IDEFS. I'm not sure if IDEFS is just alias to ADFS or different. 
It's better not to use github fosh such topics. Please use MiSTer forum for discussions.

**Comment by PaulSpek** [comment]
Thanks for pointing to the forums. Apparently the Archie core is a bit picky on the hdf format.

IDEFS uses the ADFS file system format, as do most filing systems for RiscOS.
